### ISSUE TITLE
Lazy loading the plugin -- this costs ~25ms on startup

### ISSUE THREAD

**Issue by lanza** [theHamsta/nvim-dap-virtual-text#11]
Not a huge deal obviously as that's not too much time, but from measuring with `nvim --startuptime` `nvim-dap-virtual-text` adds 22-30-ish ms on startup but doesn't do anything until `nvim-dap` is in use (which is a relatively uncommon thing anyways). Lazily loading this plugin would be a nice improvement.

**Comment by theHamsta** [comment]
Yes, this plugin requires `dap` and now also nvim-treesitter (was defered before). Requiring those big plugins can take some time. I could just remove https://github.com/theHamsta/nvim-dap-virtual-text/blob/master/plugin/nvim-dap-virtual-text.vim

**Comment by theHamsta** [comment]
@mfussenegger could we move the listeners to a separate file that is required by `dap.lua`? This would enable `setup` calls in dap-ui or in this plugin to set their listeners without requiring all of nvim-dap on start-up (where usually `setup` is called). They still could be exposed in `dap.lua` for API stability.

**Comment by mfussenegger** [comment]
Depending on how users configure nvim-dap it would still end up being imported on startup, so I am not sure if moving the listeners into a separate file is the best option.

I created a [PR](https://github.com/mfussenegger/nvim-dap/pull/199) to lazy load the internal modules. On my machine `require('dap')` now takes ~1ms, which I think is good enough?

**Comment by theHamsta** [comment]
@lanza could you try the of  @mfussenegger and the PR in this repo whether they solve your problem? I guess most of the time of this plugin might be importing nvim-treesitter which is now deferred.

**Comment by lanza** [comment]
Seems to drop down to ~14ms. Solid improvement. For context, these are my 3 slowest loading plugins:

```
011.149: sourcing /Users/lanza/.local/share/nvim/plugged/nerdtree/plugin/NERD_tree.vim
013.933: sourcing /Users/lanza/.local/share/nvim/plugged/nvim-dap-virtual-text/plugin/nvim-dap-virtual-text.vim
018.068: sourcing /Users/lanza/Projects/vim-polyglot/autoload/polyglot/init.vim
```

**Comment by theHamsta** [comment]
@lanza does this include #12 ? With #12 you should be able to prevent loading of nvim-dap-virtual-text by setting `g:nvim_dap_virtual_text_loaded`. I don't know whether I want to make this the default yet. To activate the plugin just require `nvim-dap-virtual-text`

**Comment by lanza** [comment]
> @lanza does this include #12 ? With #12 you should be able to prevent loading of nvim-dap-virtual-text by setting g:nvim_dap_virtual_text_loaded. I don't know whether I want to make this the default yet. To activate the plugin just require nvim-dap-virtual-text

Yup, that brings the load time to a negligible amount. Thank you for looking into this!
