### ISSUE TITLE
ignore signal SIGWINCH

### ISSUE THREAD

**Issue by igorlfs** [theHamsta/nvim-dap-virtual-text#13]
This is mostly an annoyance, but currently, I'd say the plugin doesn't handle very well a SIGWINCH[[1](https://www.gnu.org/software/libc/manual/html_node/Miscellaneous-Signals.html)]. If a SIGWINCH happens, the plugin will display it in every single debugging step. Apologies if this is the intended behavior, as I imagine it might be useful in some cases. However, it clutters the view when debugging using an external terminal, as it's not unusual to resize splits/windows for whatever reason.

**Comment by theHamsta** [comment]
This should deactivate the virtual text

```
require "nvim-dap-virtual-text/virtual_text".set_error = function() end
```
or
```
require'nvim-dap-virtual-text'
require'dap'.listeners.after.exceptionInfo['nvim-dap-virtual-text'] = function() end
```

I should add an option for it

**Comment by igorlfs** [comment]
Hello there!
Thanks,
>require "nvim-dap-virtual-text/virtual_text".set_error = function() end

works like a charm!
