### ISSUE TITLE
Is there anyone sample configuration, I am a rookie

### ISSUE THREAD

**Issue by denstiny** [theHamsta/nvim-dap-virtual-text#2]

**Comment by theHamsta** [comment]
Hi, there is no real configuration necessary. It will just work when you have `nvim-dap` and `nvim-tresitter` installed.

The only configuration is the following global variable.

Paste this in you `init.vim` to activate the plugin

```
let g:dap_virtual_text=v:true
```
or in a `init.lua`
```
vim.g.dap_virtual_text = true
```

**Comment by denstiny** [comment]
ok, Let me try,Reply later

**Comment by denstiny** [comment]
Well, I do not understand the configuration of dap
![image](https://user-images.githubusercontent.com/57088952/106420081-d9fb6200-6494-11eb-8dfd-d3a21e163024.png)

**Comment by denstiny** [comment]
![image](https://user-images.githubusercontent.com/57088952/106454631-07143880-64c6-11eb-9ad4-285eb7dff819.png)
#  I think I configuration succeeded, but seemed very strange, I did not show its value, but shows the address of it

**Comment by theHamsta** [comment]
@denstiny but it's the decission of the debug adapter on what to show for the value of a variable. Some of them let you configure how to represent variables (I think vscode-cpp lldb-vscode don't let you do that). You can see the actual value of a string by using `:lua require'dap'.ui.variables.hover()` with the cursor on a variable.

**Comment by denstiny** [comment]
Ok, thank you
