### ISSUE TITLE
No text with vscode-php-adapter

### ISSUE THREAD

**Issue by panders23** [theHamsta/nvim-dap-virtual-text#27]
Hi,

currently this plugin does not work with 
[https://github.com/xdebug/vscode-php-debug](https://github.com/xdebug/vscode-php-debug).

As far I checked the reason is in a slight difference on how variables are detected/named between treesitter and xdebug. For example xdebug uses `$request` while treesitter uses `request`. 

So far i could fix the problem with a language specific workaround in `lua/nvim-dap-virtual-text/virtual_text.lua`:

```lua
  for _, s in ipairs(scopes) do
    if s.variables then
      for _, v in pairs(s.variables) do
        if lang == 'php' then
            variables[v.name:gsub("^%$", "")] = v
        else
            variables[v.name] = v
        end
      end
    end
  end
```

This only works for the function arguments, but does not show anything for inner function variables.

**Comment by theHamsta** [comment]
A more elegant solution would be to change https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/php/locals.scm to capture the `(name)` in `(variable_name name: (name) @definition.var)`

![image](https://user-images.githubusercontent.com/7189118/140317018-2b6d5189-61c7-4ebc-a3b3-95502308a6bb.png)
