### ISSUE TITLE
[Bug] Consumes too much resources and slow down with dap ui.

### ISSUE THREAD

**Issue by chriztheanvill** [theHamsta/nvim-dap-virtual-text#29]
I have installed dap, dap ui and dap virtual text.
When opens with C++, and dap ui, if expand some variable many times, neovim slow down and consume too much CPU.
![image](https://user-images.githubusercontent.com/37992958/142775850-a81e70a1-f50c-4293-9cd6-f17d4c4aa87b.png)

![image](https://user-images.githubusercontent.com/37992958/142775870-caf16fc1-3a07-4f40-bb32-f8b1326a9da7.png)

**Comment by theHamsta** [comment]
Yes, the search for the variables is done after each `variables` request and query strategy used is very slow (especially `get_scopes` and `get_definitions` which got even slower after the parent pointer was removed in tree-sitter core). When `dap-ui` does a lot of variable request, it could cause a slow down. A fix would be to make the locals API in nvim-treesitter not as slow as it is at the moment. I've never finished this one: https://github.com/nvim-treesitter/nvim-treesitter/pull/1120

I've never noticed myself any delays. Are you using `'all-scopes'`?

**Comment by rcarriga** [comment]
Just found this issue after submitting my PR but I actually think it's due to the same cause which is is fixed in #30

**Comment by theHamsta** [comment]
@chriztheanvill did @rcarriga 's PR change the situation for you?

**Comment by chriztheanvill** [comment]
Hi.
The high consume is fixed, but know I have other issues.

If virt_lines (experimental) its enabled:
![image](https://user-images.githubusercontent.com/37992958/145122964-ca821069-3e2b-4785-850e-d0382f273e47.png)

Objects does not show:
![image](https://user-images.githubusercontent.com/37992958/145123287-40d9a4e3-7b87-4c6d-a076-2e0a93911f58.png)

**Comment by theHamsta** [comment]
Ok, when the high-resource consumption is fixed, we can close this issue. I will have a look at the bug you reported. But it'll probably take time until next year until I'll find time for it (and I have my computer back, I'm on vacation right now)
