### ISSUE TITLE
Visual text missing with git-blame

### ISSUE THREAD

**Issue by Mte90** [theHamsta/nvim-dap-virtual-text#3]
I am using also this plugin `f-person/git-blame.nvim` and uses virtual-text but I get just this also if the variable is turned true.

**Comment by theHamsta** [comment]
At least my plugin can coexist with built-in LSP
![image](https://user-images.githubusercontent.com/7189118/111512057-a1b39880-874f-11eb-827f-70f21f099ace.png)

So it should be possible to have virtual text from different plugins

**Comment by Mte90** [comment]
I think that I misunderstood the plugin purpose -.-'

I was thinking that show the variables got by dap instead of executing that line also require a command to run inside neovim to get the value, so it is normal that anything is printed...

**Comment by theHamsta** [comment]
No, it will get all variables by DAP and resolve the location via nvim-treesitter.

**Comment by Mte90** [comment]
So I have to run the DAP command and see what is working.

**Comment by theHamsta** [comment]
It shows you the values of variables when the debugger is stopped.

**Comment by f-person** [comment]
Yes, the namespace is is hardcoded to `2` in `git-blame.nvim`. I'll change it to be exclusive by this method and you can close the issue if it fixes the problem.

**Comment by f-person** [comment]
@Mte90 I've updated git-blame.nvim to use `vim.api.nvim_create_namespace` instead of hardcoding the namespace id. Can you please update the plugin and check if it's okay now?
