### ISSUE TITLE
Virtual text appears only for previous lines 

### ISSUE THREAD

**Issue by balazser** [theHamsta/nvim-dap-virtual-text#34]
The virtual text is shown for a variable only on the previous lines during debugging. (1)
On the attached screenshot, `new_value` 's value is not shown for the current line (3), only the definition preceding it.  (2)
Is this something expected?  :thinking:  The value `c` is printed for every line in your README demo.

The snippet is inside a for loop in which the first  `new_value` (1) is updated in the previous iteration than (2).

![image](https://user-images.githubusercontent.com/20303564/165814258-14deb71d-7a37-4a38-8a4c-624abcf525a1.png)

**Comment by theHamsta** [comment]
I remember changing the algorithm to only show the value once at the definition. It would be no problem to show the value on every reference. I can offer this as a config option as it might make the virtual text a lot more cluttered.

**Comment by balazser** [comment]
Hey @theHamsta , it would be awesome! :pray: 
Many thanks for this awesome plugin!

**Comment by theHamsta** [comment]
Just if you want to experiment: https://github.com/theHamsta/nvim-dap-virtual-text/pull/35

If you want to have virtual text at all references (not only definition)
![grafik](https://user-images.githubusercontent.com/7189118/165999407-f33eb76e-d550-476f-a124-0c6908868853.png)

Has also some charm, I'm thinking about how to expose those options. I'm at the moment not able to easily filter out Python modules for references (would require looking up their definition or checking whether they are present in the globals section of the DAP variables)

**Comment by theHamsta** [comment]
Should be fixed by #35. Didn't mean to merge it yet, but apparently it happened.

**Comment by balazser** [comment]
Hey @theHamsta, thanks for the update! It looks awesome. :rocket: 
Also, thanks for the plugin. I prefer the `nvim-dap-virtual-text` debugging experience better than the ordinary side panel one.
