### ISSUE TITLE
Does not show actual values for recursive calls

### ISSUE THREAD

**Issue by balazser** [theHamsta/nvim-dap-virtual-text#37]
It seems `[nvim-dap-virtual-text](https://github.com/theHamsta/nvim-dap-virtual-text)` shows only the values of the first method call and does not update on recursive call.
 
![image](https://user-images.githubusercontent.com/20303564/169710183-2d4f2b56-cf2a-4022-8976-c11e8a56a84f.png)

```python
class Solution:
    def isValidBST(self, root: Optional[TreeNode]) -> bool:
        # validation
        if not root:
            return True

        left = True
        if root.left:
            if root.left.val < root.val:
                left = True and self.isValidBST(root.left)
            else:
                left = False

        right = True
        if root.right:
            if root.right.val > root.val:
                right = True and self.isValidBST(root.right)
            else:
                left = False

        return left and right


root = to_binary_tree([5, 4, 6, None, None, 3, 7])

# test cases
result = Solution().isValidBST(root)
assert not result

```

**Comment by theHamsta** [comment]
I could not reproduce with 
```
def recursive_add(n):
    if n == 0:
        return 0
    else:
        return n + recursive_add(n - 1)


recursive_add(10)
```
Can you provide `to_binary_tree` so I can test your example? I actually try to detect recursive calls in when `all_frames = true`. But as mentioned the feature is experimental. I think the behavior that I intended it to have on recursive call is to take the stack values of the inner-most call.
