### ISSUE TITLE
Allow filter by name too

### ISSUE THREAD

**Issue by przepompownia** [theHamsta/nvim-dap-virtual-text#47]
Hi @theHamsta 

I looked how `filter_references_pattern` works and see that it [filters the value](https://github.com/theHamsta/nvim-dap-virtual-text/blob/master/lua/nvim-dap-virtual-text/virtual_text.lua#L102) of evaluated variable. 

I'd like to hide `this` - in most cases it's not needed for me. 

What do you think about adding filters for names too?

**Comment by przepompownia** [comment]
Maybe it'd be good to can distinguish filters by language too.

**Comment by theHamsta** [comment]
Fixed by #50
