### ISSUE TITLE
Ideas how to customize the output (per language)

### ISSUE THREAD

**Issue by przepompownia** [theHamsta/nvim-dap-virtual-text#48]
Example from PHP: any object of class that implements `JsonSerializable` could be rendered as the result of `json_encode` on it. 

I have no idea that looks possibly good. 

I thought about a callback that would be provided by the user to convert the variable to the desired form. It could use `dap.session():evaluate()` but I have doubt how practical is it.

**Comment by theHamsta** [comment]
Until now, I tried to avoid `dap.session():evaluate() ` as I tried to be a passive plugin that does not modify your debug state. Evaluate can possibly modify the application state and can be costly. I'm just relying on the printed value of the top-level scope.

It could be an `opt-in` setting to use `dap.session():evaluate() ` , also for `this->XXX` which I'm currently not catching.

**Comment by przepompownia** [comment]
I did not suggested to include any implementation containing `dap.session():evaluate()` in the plugin - only in any custom function at the user's own risk. It would be good to only have such possibility - not by default.

**Comment by theHamsta** [comment]
Is this fixed by #50 or do you need more to also account for the async nature of `dap.session():evaluate()`

**Comment by przepompownia** [comment]
I still wait for more free time to focus on it.
