### ISSUE TITLE
Virtual text in scala showing at incorrect position for function arguments

### ISSUE THREAD

**Issue by ghostbuster91** [theHamsta/nvim-dap-virtual-text#55]
Hi, 

I am trying to integrate this plugin with scala and I noticed that the virtual text for function arguments is displayed incorrectly if earlier in the file there is another function that contains argument with the same name. 

![image](https://user-images.githubusercontent.com/5662622/229157010-8e0029cc-2f6f-47b5-83cb-56d8020964f1.png)

Here are definitions for nvim-treesitter locals:
```scheme
[(block)
(template_body)
(lambda_expression)
(function_declaration)] @scope

(function_declaration
  name: (identifier) @definition.function)

(val_definition
  pattern: (identifier) @definition.var)

(parameters (parameter name: (identifier) @definition.parameter ))

```

Any idea what could be the reason?
Btw scope detection works correctly for local variables defined within the function. 
In the attached example `var2` is detected correctly.

**Comment by theHamsta** [comment]
@ghostbuster91 someone else reported this earlier. Is this still an issue? Scala had missing `@scope` definitions in nvim-treesitter which are needed to recogonize functions as separated scopes with their own set of variables.

**Comment by ghostbuster91** [comment]
@theHamsta Yes, I was aware of incomplete treesitter definitions for scala. I wrote the mentioned snippet and included it locally. The snipped contained correct (to the best of my knowledge) definitions of `@scope`. 

I am also certain that the snipped was correctly loaded by neovim because there were other definitions missing like `@definition.var` in the upstream that I had locally defined and I was able to see runtime values for variable definitions.

**Comment by ghostbuster91** [comment]
I confirm, the issue still occurs. I will provide later a small reproducible example.

**Comment by theHamsta** [comment]
> @theHamsta Yes, I was aware of incomplete treesitter definitions for scala. I wrote the mentioned snippet and included it locally. The snipped contained correct (to the best of my knowledge) definitions of `@scope`.
> 
> I am also certain that the snipped was correctly loaded by neovim because there were other definitions missing like `@definition.var` in the upstream that I had locally defined and I was able to see runtime values for variable definitions.
> 
> Having said that, I don't know if this is still an issue, let my try to reproduce it.

Did you submit the fix to nvim-treesitter?

**Comment by ghostbuster91** [comment]
I wanted to but Chris was faster https://github.com/nvim-treesitter/nvim-treesitter/pull/4567

**Comment by ghostbuster91** [comment]
Here is code from the snippet slightly simplified: 

```scala
  def other(var1: String) = {
    val var2 = var1.trim()
    var2
  }

  def result(var1: String): Either[String, Unit] = {
    val var2 = var1.trim()
    Left(var2)
  }

```


and its representation seen by the treesitter:
```
    function_definition [12, 2] - [15, 3]
      name: identifier [12, 6] - [12, 11]
      parameters: parameters [12, 11] - [12, 25]
        parameter [12, 12] - [12, 24]
          name: identifier [12, 12] - [12, 16]
          type: type_identifier [12, 18] - [12, 24]
      body: block [12, 28] - [15, 3]
        val_definition [13, 4] - [13, 26]
          pattern: identifier [13, 8] - [13, 12]
          value: call_expression [13, 15] - [13, 26]
            function: field_expression [13, 15] - [13, 24]
              value: identifier [13, 15] - [13, 19]
              field: identifier [13, 20] - [13, 24]
            arguments: arguments [13, 24] - [13, 26]
        identifier [14, 4] - [14, 8]
    function_definition [17, 2] - [20, 3]
      name: identifier [17, 6] - [17, 12]
      parameters: parameters [17, 12] - [17, 26]
        parameter [17, 13] - [17, 25]
          name: identifier [17, 13] - [17, 17]
          type: type_identifier [17, 19] - [17, 25]
      return_type: generic_type [17, 28] - [17, 48]
        type: type_identifier [17, 28] - [17, 34]
        type_arguments: type_arguments [17, 34] - [17, 48]
          type_identifier [17, 35] - [17, 41]
          type_identifier [17, 43] - [17, 47]
      body: block [17, 51] - [20, 3]
        val_definition [18, 4] - [18, 26]
          pattern: identifier [18, 8] - [18, 12]
          value: call_expression [18, 15] - [18, 26]
            function: field_expression [18, 15] - [18, 24]
              value: identifier [18, 15] - [18, 19]
              field: identifier [18, 20] - [18, 24]
            arguments: arguments [18, 24] - [18, 26]
        call_expression [19, 4] - [19, 14]
          function: identifier [19, 4] - [19, 8]
          arguments: arguments [19, 8] - [19, 14]
            identifier [19, 9] - [19, 13]
```

I now noticed that my local definitions were in fact missing entry for `function_definition` (I had only `function_declaration`), but the upstream contains correct entries and I also tested that running `vim --cmd "set rtp+=./" locally with queries that contains `function_definition` scope still runs into the issue.

**Comment by ghostbuster91** [comment]
I found it. Of course it was a problem with missing scope :upside_down_face: 

There is a scope for `function_declaration` but it should be `function_definition` because the first one does not introduce scope. 

It was quite hard to spot due to naming similarity.

**Comment by ghostbuster91** [comment]
Fix is on the way: https://github.com/nvim-treesitter/nvim-treesitter/pull/4723

**Comment by theHamsta** [comment]
> I found it. Of course it was a problem with missing scope 🙃
> 
> There is a scope for `function_declaration` but it should be `function_definition` because the first one does not introduce scope.
> 
> It was quite hard to spot due to naming similarity.
> 
> Sorry for bothering you unnecessary.

Thanks for fixing it! Please note that the algorithm of this repo is also very naive so it will not handle every. Until now it was good enough for most cases.
