### ISSUE TITLE
Invalid 'virt_text_pos'

### ISSUE THREAD

**Issue by fredrikaverpil** [theHamsta/nvim-dap-virtual-text#61]
I'm getting this error every time I step forward when debugging:

![image](https://github.com/LazyVim/LazyVim/assets/994357/282df24a-8ea7-4685-a214-4db6aa0b0d27)

```
Error executing vim.schedule lua callback: ...-virtual-text/lua/nvim-dap-virtual-text/virtual_text.lua:213: Invalid 'virt_text_pos'
stack traceback:
	[C]: in function 'nvim_buf_set_extmark'
	...-virtual-text/lua/nvim-dap-virtual-text/virtual_text.lua:213: in function 'set_virtual_text'
	...lazy/nvim-dap-virtual-text/lua/nvim-dap-virtual-text.lua:112: in function 'c'
	...k/.local/share/LazyVim/lazy/nvim-dap/lua/dap/session.lua:953: in function <...k/.local/share/LazyVim/lazy/nvim-dap/lua/dap/session.lua:947>
```

## Workaround

I can get rid of this problem entirely by removing the `display_callback`:

```lua
{
    "theHamsta/nvim-dap-virtual-text",
    config = function()
        require("nvim-dap-virtual-text").setup({
            display_callback = function(variable, buf, stackframe, node, options) end,
        })
    end,
},
```

Or I can make sure to use the 10f858c402eb985739627b7e69a38f5b2d79076b commit of `nvim-dap-virtual-text`.

## My setup

I'm using LazyVim which loads `nvim-dap-virtual-text` itself (see [here](https://www.lazyvim.org/plugins/extras/dap.core#nvim-dap-virtual-text)) as I've [enabled](https://github.com/fredrikaverpil/dotfiles/blob/main/nvim-lazyvim/lua/config/lazy.lua#L21) LazyVim's "DAP Core" (which installs nvim-dap and friends).

On top of that I've got [these DAP settings](https://github.com/fredrikaverpil/dotfiles/blob/main/nvim-lazyvim/lua/plugins/debug.lua) and [these neotest settings](https://github.com/fredrikaverpil/dotfiles/blob/main/nvim-lazyvim/lua/plugins/test.lua). My entire neovim config is available in my dotfiles repo [here](https://github.com/fredrikaverpil/dotfiles/blob/main/nvim-lazyvim/lua).

## Print debugging

I added a print statement before the "offending" line at `virtual_text.lua:213`:

```lua
print(options.virt_text_pos, buf, hl_namespace, node_range[inline and 3 or 1], node_range[inline and 4 or 2])
```

```
08:03:23 msg_show inline 1 147 10 10
   Error  08:03:23 msg_show.lua_error Error executing vim.schedule lua callback: ...-virtual-text/lua/nvim-dap-virtual-text/virtual_text.lua:217: Invalid 'virt_text_pos'
stack traceback:
	[C]: in function 'nvim_buf_set_extmark'
	...-virtual-text/lua/nvim-dap-virtual-text/virtual_text.lua:217: in function 'set_virtual_text'
	...lazy/nvim-dap-virtual-text/lua/nvim-dap-virtual-text.lua:112: in function 'c'
	...k/.local/share/LazyVim/lazy/nvim-dap/lua/dap/session.lua:953: in function <...k/.local/share/LazyVim/lazy/nvim-dap/lua/dap/session.lua:947>
08:03:23 msg_show inline 1 147 10 10
   Error  08:03:23 msg_show.lua_error Error executing vim.schedule lua callback: ...-virtual-text/lua/nvim-dap-virtual-text/virtual_text.lua:217: Invalid 'virt_text_pos'
stack traceback:
	[C]: in function 'nvim_buf_set_extmark'
	...-virtual-text/lua/nvim-dap-virtual-text/virtual_text.lua:217: in function 'set_virtual_text'
	...lazy/nvim-dap-virtual-text/lua/nvim-dap-virtual-text.lua:112: in function 'c'
	...k/.local/share/LazyVim/lazy/nvim-dap/lua/dap/session.lua:953: in function <...k/.local/share/LazyVim/lazy/nvim-dap/lua/dap/session.lua:947>
08:03:23 msg_show inline 1 147 10 10
   Error  08:03:23 msg_show.lua_error Error executing vim.schedule lua callback: ...-virtual-text/lua/nvim-dap-virtual-text/virtual_text.lua:217: Invalid 'virt_text_pos'
stack traceback:
	[C]: in function 'nvim_buf_set_extmark'
	...-virtual-text/lua/nvim-dap-virtual-text/virtual_text.lua:217: in function 'set_virtual_text'
	...lazy/nvim-dap-virtual-text/lua/nvim-dap-virtual-text.lua:112: in function 'c'
	...k/.local/share/LazyVim/lazy/nvim-dap/lua/dap/session.lua:953: in function <...k/.local/share/LazyVim/lazy/nvim-dap/lua/dap/session.lua:947>
08:03:23 msg_show inline 1 147 10 10
   Error  08:03:23 msg_show.lua_error Error executing vim.schedule lua callback: ...-virtual-text/lua/nvim-dap-virtual-text/virtual_text.lua:217: Invalid 'virt_text_pos'
stack traceback:
	[C]: in function 'nvim_buf_set_extmark'
	...-virtual-text/lua/nvim-dap-virtual-text/virtual_text.lua:217: in function 'set_virtual_text'
	...lazy/nvim-dap-virtual-text/lua/nvim-dap-virtual-text.lua:112: in function 'c'
	...k/.local/share/LazyVim/lazy/nvim-dap/lua/dap/session.lua:953: in function <...k/.local/share/LazyVim/lazy/nvim-dap/lua/dap/session.lua:947>

```

## Solution

Can you see what's going on here - and/or what can be done to fix this?

## Linked discussion

https://github.com/LazyVim/LazyVim/discussions/821

**Comment by theHamsta** [comment]
Are you using Neovim nightly? The "inline" value for `virt_text_pos` was introduced two days ago. It should only be used with `has('nvim-0.10')` and not on released versions. When you are using nightly please use a newer version.

**Comment by fredrikaverpil** [comment]
Oh, that was it. I was using nightly, but I did not intend to do so.

Thank you @theHamsta!

**Comment by theHamsta** [comment]
> Oh, that was it. I was using nightly, but I did not intend to do so.
> 
> Thank you @theHamsta!

It's a cool feature to try out. Would love to get feedback on it when you get the time to try it out. It just requires a nightly build from today. `vim.fn.has 'nvim-0.10' == 1 and 'inline' or 'eol'` would enable the feature by default when you are on nightly.
