### ISSUE TITLE
[feature request] Ability to set virtual-text colour

### ISSUE THREAD

**Issue by quantum-booty** [theHamsta/nvim-dap-virtual-text#8]
Currently the virtual text have the same colour to comments, the ability to set its colour brighter would improve readability.
![image](https://user-images.githubusercontent.com/28958399/117371004-205ec380-aebf-11eb-8d07-5385a4572baf.png)

**Comment by theHamsta** [comment]
Hi. You already can do that. The syntax highlight group is `NvimDapVirtualText`.

So you can do to set `guifg` and `guibg` 
```
highlight NvimDapVirtualText guibg=#000099
```
or
```
highlight NvimDapVirtualText link Type
```
to give it the highlight of `Type` instead of `Comment`

**Comment by quantum-booty** [comment]
I doubt one can choose a single colour that is compatible in appearance with all colour schemes, I've just picked one (#82E0AA) from this site:
https://htmlcolorcodes.com/
![image](https://user-images.githubusercontent.com/28958399/117373384-045d2100-aec3-11eb-9218-a68b915e5d09.png)

**Comment by theHamsta** [comment]
You're right. This color looks nice :smile: I'll also use it for my personal config.
