### ISSUE TITLE
Plugin throws a nil value error

### ISSUE THREAD

**Issue by Espacio-root** [theHamsta/nvim-dap-virtual-text#85]
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/treesitter.lua:182: attempt to call method 'range' (a nil value)
stack traceback:
	/usr/share/nvim/runtime/lua/vim/treesitter.lua:182: in function 'get_range'
	/usr/share/nvim/runtime/lua/vim/treesitter.lua:217: in function 'get_node_text'
	...-virtual-text/lua/nvim-dap-virtual-text/virtual_text.lua:165: in function 'set_virtual_text'
	...lazy/nvim-dap-virtual-text/lua/nvim-dap-virtual-text.lua:114: in function 'c'
	...acio/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1002: in function <...acio/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:996>

I'm using nvim nightly.
NVIM v0.11.0-dev-711+g7b7c95dac

**Comment by b0o** [comment]
Hi @Espacio-root, can you see if #87 fixes this for you?

**Comment by Espacio-root** [comment]
@b0o Yes! It works as expected on my end. Closing now..
