### ISSUE TITLE
need help: dap debug go err:  virtual_text.lua:132: bad argument #1 to pairs table expected, got userdata

### ISSUE THREAD

**Issue by hellohake** [theHamsta/nvim-dap-virtual-text#88]
<img width="1913" alt="image" src="https://github.com/user-attachments/assets/be3be187-26a5-4805-8155-baf288c776a4">

nvim version: 
<img width="951" alt="image" src="https://github.com/user-attachments/assets/cd74a81f-9499-4d4a-aa37-b2214bd8d252">
lua version:
<img width="662" alt="image" src="https://github.com/user-attachments/assets/b59c0b9e-c18c-4373-b7c8-ca2520c4847c">

when i debug go program using dap-go,  if with breakpoint the error happen,  when without breakpoint error not occur

i use lazyvim manager my nvim plugins, the dap relative plugin config is below:
---
`local custom = {}

custom["leoluz/nvim-dap-go"] = {
	"leoluz/nvim-dap-go",
	dependencies = {
		"mfussenegger/nvim-dap",
	},
	config = function()
		require("dap-go").setup()
	end,
}

custom["rcarriga/nvim-dap-ui"] = {
	"rcarriga/nvim-dap-ui",
	dependencies = {
		"nvim-neotest/nvim-nio",
	},
}

custom["theHamsta/nvim-dap-virtual-text"] = {
	"theHamsta/nvim-dap-virtual-text",
	dependencies = {
		"mfussenegger/nvim-dap",
		"nvim-treesitter/nvim-treesitter",
	},
	init = function()
		require("nvim-dap-virtual-text").setup({
			enabled = true,
			enabled_commands = true,
			highlight_changed_variables = true,
			highlight_new_as_changed = true,
			virt_text_pos = "eol",
			commented = true,
		})
	end,
}
custom["nvim-telescope/telescope-dap.nvim"] = {
	"nvim-telescope/telescope-dap.nvim",
	dependencies = {
		"mfussenegger/nvim-dap",
	},
}

custom["mfussenegger/nvim-dap"] = {
	"mfussenegger/nvim-dap",
	dependencies = {
		"rcarriga/nvim-dap-ui",
	},
	keys = {
		{
			"<F5>",
			function()
				require("telescope").extensions.dap.configurations()
			end,
			mode = { "n" },
			desc = "debug",
		},
		{
			"<F6>",
			function()
				require("dap").terminate()
			end,
			mode = { "n" },
			desc = "debug",
		},
		{
			"<F12>",
			function()
				require("dap").step_over()
			end,
			mode = { "n" },
			desc = "debug",
		},
		{
			"<F10>",
			function()
				require("dap").step_into()
			end,
			mode = { "n" },
			desc = "debug",
		},
		{
			"<F11>",
			function()
				require("dap").step_out()
			end,
			mode = { "n" },
			desc = "debug",
		},
		{
			"<Leader>db",
			function()
				require("dap").toggle_breakpoint()
			end,
			mode = { "n" },
			desc = "debug",
		},
		{
			"<Leader>dl",
			function()
				require("dap").run_last()
			end,
			mode = { "n" },
			desc = "debug",
		},
	},
	config = function()
		local dap, dapui = require("dap"), require("dapui")
		dapui.setup()
		dap.listeners.before.attach.dapui_config = function()
			dapui.open()
		end
		dap.listeners.before.launch.dapui_config = function()
			dapui.open()
		end
		dap.listeners.before.event_terminated.dapui_config = function()
			dapui.close()
		end
		dap.listeners.before.event_exited.dapui_config = function()
			dapui.close()
		end
	end,
}

return custom
`

**Comment by fengwk** [comment]
I encountered the same problem

**Comment by hellohake** [comment]
> I encountered the same problem and it can be solved by rolling back to [9578276](https://github.com/theHamsta/nvim-dap-virtual-text/commit/9578276dfdc5420624699744377ddd74be2d9a19)

it's useful for me

**Comment by theHamsta** [comment]
I think the problem is #87. Could you check whether https://github.com/theHamsta/nvim-dap-virtual-text/pull/89 would help?

I knew that #87 would break compatibility for older nvim versions, but also wanted to follow Neovim's new API. Sorry that I did not have time to use this plugin for a longer time. Also above PR was not tested yet by me.

**Comment by theHamsta** [comment]
Verified that #89 fixes the issue. On master:
```
Error executing vim.schedule lua callback: ...-virtual-text/lua/nvim-dap-virtual-text/virtual_text.lua:130: bad argument #1 to 'pairs' (table expected, got userdata)
stack traceback:
        [C]: in function 'pairs'
        ...-virtual-text/lua/nvim-dap-virtual-text/virtual_text.lua:130: in function 'fn'
        ...4/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:345: in function 'for_each_tree'
        ...-virtual-text/lua/nvim-dap-virtual-text/virtual_text.lua:125: in function 'set_virtual_text'
        ...lazy/nvim-dap-virtual-text/lua/nvim-dap-virtual-text.lua:114: in function 'c'
        ...phan/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1027: in function <...phan/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1021>
```
and working as expected with the fix.
