### ISSUE TITLE
attempt to index local body (nil value ) error

### ISSUE THREAD

**Issue by JoseConseco** [theHamsta/nvim-dap-virtual-text#9]
Hello I'm getting this error quite a bit recently:
![image](https://user-images.githubusercontent.com/13521338/118404626-f56d3000-b673-11eb-9fdb-c8fe425f981b.png)

my config:
```lua
vim.g.dap_virtual_text = 'all frames'  -- 'all frames' or true or false 
```
Any ideas what is going on @theHamsta  ?

**Comment by theHamsta** [comment]
Which debug adapter are you using? I haven't found one yet that really supports all frames. Debug-py allows you to ask for other frames than the current but looses some of the requests on the way.

So in doubt just stay with "true"

Anyways I can fix the error message that indicates that the debug adapter didn't give an answer to our request.

**Comment by JoseConseco** [comment]
HI, I'm using debugpy, and setting the dap_virtual_text to True  fixed the issue. Thanks for the help and plugin.
I think it is good to have notification that something is wrong with dap answer, but the way vim works - if you have more than one error in command line, then nvim always display 'press somthing to continue' which is supper annoying - I cant debug like this when error pops every second

**Comment by JoseConseco** [comment]
I'm thinking if maybe you could display the error once -then mute it - so nvim wont constantly ask  for key press to continue? This way user would know somehting if off, but he will be able to work.

**Comment by theHamsta** [comment]
I usually just don't display anything if there's an error. This should also be the response for no answer.

**Comment by theHamsta** [comment]
@JoseConseco does #10 make the error disappear?

**Comment by JoseConseco** [comment]
@theHamsta  Yes the issue is gone. Thanks for the fix! I'm not sure if the issue is debugpy  or that I'm using remote attach to external process for debugging. In any case it works ok now. I think I did not had any problem when using debugpy  'run python file' config. But I leave the decision up to you

**Comment by theHamsta** [comment]
Just tried the feature "all-frames" again. It seems to work, but whenever you encounter any missing frames it might be because debugy does not respond to all request if there are to many at once. Then you could just use "true" which at least gives you always the current frame.
